// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEWuiQdQ1y57IINEtWmvgOBo-5gz6I5Q',
    appId: '1:204830564235:web:8fc617134985520e73198e',
    messagingSenderId: '204830564235',
    projectId: 'keke-fairshare',
    authDomain: 'keke-fairshare.firebaseapp.com',
    storageBucket: 'keke-fairshare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbb_6PRYKqDnR8GgtEbpT8qZ6Wpy9Dx0I',
    appId: '1:204830564235:android:c95a0d7354de30ae73198e',
    messagingSenderId: '204830564235',
    projectId: 'keke-fairshare',
    storageBucket: 'keke-fairshare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZesea_Cg5uB6Cn1pvcRettN8c-TCNGoE',
    appId: '1:204830564235:ios:a4793253e5e33f4973198e',
    messagingSenderId: '204830564235',
    projectId: 'keke-fairshare',
    storageBucket: 'keke-fairshare.firebasestorage.app',
    iosBundleId: 'com.example.kekeFairshare',
  );
}
